<a href="https://colab.research.google.com/github/Chaqmoqjon/NumPY/blob/main/10_Arr_Or_Pr_4_Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.random.rand(4)  # 0 va 1 oralig'idagi random sonlar
arr

array([0.61285851, 0.28081987, 0.02085002, 0.33971486])

In [ ]:
# 1-usul
sorted_arr = np.sort(arr)  # tartiblab o'zgaruvchiga saqlaydi
sorted_arr

array([0.02085002, 0.28081987, 0.33971486, 0.61285851])

In [ ]:
# 2- usul
arr.sort()  # yangidan tartiblab joylaydi
arr

array([0.02085002, 0.28081987, 0.33971486, 0.61285851])

In [ ]:
rev_arr = -np.sort(-arr) # teskari tartibda tartiblash
rev_arr

array([0.61285851, 0.33971486, 0.28081987, 0.02085002])

In [ ]:
arr2d = np.random.randn(2, 4)
arr2d

array([[ 0.47115108,  1.60604069,  0.26625441, -0.20538351],
       [ 0.40894718, -0.26683279,  2.38829654,  1.70063403]])

In [ ]:
col_sort = np.sort(arr2d, axis = 0) # ustunlar bo'yicha tartiblash
col_sort

array([[ 0.40894718, -0.26683279,  0.26625441, -0.20538351],
       [ 0.47115108,  1.60604069,  2.38829654,  1.70063403]])

In [ ]:
row_sort = np.sort(arr2d, axis = 1)  # qatorlarga ko'ra tartiblash (default axis)
row_sort

array([[-0.20538351,  0.26625441,  0.47115108,  1.60604069],
       [-0.26683279,  0.40894718,  1.70063403,  2.38829654]])