<a href="https://colab.research.google.com/github/Chaqmoqjon/NumPY/blob/main/12_Save_Load.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.save('data', arr1) # ma'lumotni saqlash

In [ ]:
arr_read1 = np.load('data.npy') # saqlangan ma'lumotni chaqirish
arr_read1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr2 = np.arange(20)
arr3 = np.arange(25)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.savez('data_more',  a = arr1, b = arr2, c = arr3)  # 2 va undan ortiq datani saqlash uchun

In [ ]:
arr_read_more = np.load('data_more.npz')  # saqlangan ma'lumotni chaqirish

In [ ]:
arr_read_more['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr_read_more['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr_read_more['c']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
np.savez_compressed("compress_data", a = arr1, arr2 = arr2)  # datani kichraytirib saqlash

In [ ]:
arr_compress = np.load('compress_data.npz')

In [ ]:
arr_compress['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr_compress['arr2']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])