<a href="https://colab.research.google.com/github/Chaqmoqjon/NumPyLesson001/blob/main/1_creating_arreys.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
data1 = [3.5, 6, 8, 1]  #list
arr1 = np.array(data1)  #arr

In [ ]:
data1

[3.5, 6, 8, 1]

In [ ]:
arr1

array([3.5, 6. , 8. , 1. ])

In [ ]:
data2 = (2, 4, 6, 8, 8)
arr2 = np.array(data2)

In [ ]:
arr2

array([2, 4, 6, 8, 8])

In [ ]:
arr2.ndim   #arrayning o'lchami

1

In [ ]:
data3 = [[1, 2, 3, 4, 5],
         [6, 7, 8, 9, 0]]
arr3 = np.array(data3)

arr3.ndim   #arrayning o'lchami

2

In [ ]:
matrix_3d = [
    [
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10]
    ],
    [
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]
    ]
]
arr_3d = np.array(matrix_3d)

arr_3d.ndim   #arrayning o'lchami

3

In [ ]:
arr3.shape  #qator va ustunlar soni (q, u)

(2, 5)

In [ ]:
arr3.size  #elementlar soni

10

In [ ]:
arr4 = np.zeros((2, 4))  #barcha elementlari 0 ga teng array
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr5 = np.ones((3, 5))  #barcha elementlari 1 ga teng array
arr5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arr5.ndim

2

In [ ]:
arr6 = np.arange(4, 40, 2)  # 4 dan 40 gacha 2 qadam bilan massivga joylaydi
arr6

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38])

In [ ]:
def one_dim(n):
    massiv = np.arange(n)
    return massiv

print(one_dim(10))

[0 1 2 3 4 5 6 7 8 9]
