<a href="https://colab.research.google.com/github/Chaqmoqjon/MohirdevNumPY/blob/main/3_Indexing%26Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(10, 100, 10)  #array yaratildi
arr[0]  #index 0 dan boshlanadi

90

In [ ]:
arr[3:5]  # 3 dan 5 chigacha ma'lumotlarni kesib oladi

array([40, 50])

In [ ]:
sliced_arr = arr[3:5]
sliced_arr[:] = 0   #arr ga ta'sir qiladi
sliced_arr

array([0, 0])

In [ ]:
arr  #arr ga ta'sir qiladi

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

In [ ]:
arr1 = np.arange(10, 100, 10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
sliced_array1 = arr1[3:5].copy()  #arr ga ta'sir qilmaydi
sliced_array1[:] = 0
sliced_array1

array([0, 0])

In [ ]:
arr1  #copy()  ishlatilgani uchun ta'sir qilmaydi

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
arr2d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])  # 2 o'lchamli matritsa yarataildi
arr2d.ndim

2

In [ ]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr2d[1,1]  # index ga ko'ra [1, 1] manzildagi qiymatni chiqarish

6

In [ ]:
slice_2d = arr2d[2, 2:4]  # 2 chi qatorning 2 chi ustunidan 4 chisigacha kesib bering
# slice_2d[:] = 0
slice_2d

array([0, 0])

In [ ]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  0,  0]])

In [ ]:
#3D array
arr3d = np.array([[[ 0, 1, 2 ],
                                [ 3, 4, 5 ],
                                [ 6, 7, 8 ]],
                              [ [ 9, 10, 11 ],
                                [12, 13, 14],
                                [15, 16, 17]],
                              [ [ 18, 19, 20 ],
                                [21, 22, 23],
                                [24, 25, 26]
                                           ]])
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
arr3d[0, 1, 1]  #  3 talik bersa ham bo'ladi

4

In [ ]:
arr3d[1][2, 1:] # 2D aylantirib olib ham bersa bo'ladi

array([16, 17])

In [ ]:
arr3d[2][0, :2] # 2D aylantirib olib ham bersa bo'ladi

array([18, 19])