<a href="https://colab.research.google.com/github/Chaqmoqjon/MohirdevNumPY/blob/main/4_Boolean_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
names = np.array(['Sardorbek', 'Islombek', 'Samandar', 'Ibrohimjon', 'Nomonjon', 'Akmaljon', 'Islombek'])   #array yaratildi
names

array(['Sardorbek', 'Islombek', 'Samandar', 'Ibrohimjon', 'Nomonjon',
       'Akmaljon', 'Islombek'], dtype='<U10')

In [ ]:
data = np.random.randn(7, 4)  #random sonlar yaratildi
data

array([[ 0.27984377,  0.53962617,  1.51398273, -0.13012728],
       [ 0.31901309,  0.3681482 , -3.04922905,  0.37138723],
       [-0.58031246,  1.25694581,  0.02485967,  0.0928954 ],
       [-1.18750681, -0.34246611,  0.95577529, -1.6665418 ],
       [ 0.19622189,  0.13028666, -0.73839528,  0.53451725],
       [ 0.00444716,  0.49056727,  0.59123508, -1.56253269],
       [ 0.22738966, -1.46915135,  0.471569  , -0.85743321]])

In [ ]:
names == 'Sardorbek'

array([ True, False, False, False, False, False, False])

In [ ]:
data[names == 'Sardorbek']   #data dagi Sardorbekga tegishli qatorni chiqardi

array([[-1.20978241,  0.08611968,  0.18380173, -0.76506785]])

In [ ]:
data[names == 'Islombek']  #data dagi Iskombekga tegishli qatorlarni chiqardi

array([[-0.47446401,  1.17069224,  0.18324714,  0.1094749 ],
       [ 1.21314079,  0.14050519, -0.59799566,  0.29801947]])

In [ ]:
data[names == 'Islombek', 2:]  # data dagi Islombekga tegishli ma'lumotlarning oxirgi ikkinchi ustundan boshlab hammasini chiqar

array([[ 0.18324714,  0.1094749 ],
       [-0.59799566,  0.29801947]])

In [ ]:
data[names != 'Islombek']  #data dagi Islombekga tegishli bo'lmagan ma'lumotkarni chiqarish

array([[-1.20978241,  0.08611968,  0.18380173, -0.76506785],
       [ 0.85733115, -0.75841448,  1.15107076,  0.30341557],
       [ 1.02780484,  0.22399144,  0.36981002,  0.14978213],
       [-0.21021753, -0.22334861,  1.42490542,  0.65448641],
       [ 0.91353706,  1.80050771,  0.39160595, -0.67836273]])

In [ ]:
data[~(names == 'Islombek')]  #data dagi Islombekga tegishli bo'lmagan ma'lumotkarni chiqarish

array([[-1.20978241,  0.08611968,  0.18380173, -0.76506785],
       [ 0.85733115, -0.75841448,  1.15107076,  0.30341557],
       [ 1.02780484,  0.22399144,  0.36981002,  0.14978213],
       [-0.21021753, -0.22334861,  1.42490542,  0.65448641],
       [ 0.91353706,  1.80050771,  0.39160595, -0.67836273]])

In [ ]:
print(names)
print(data)

['Sardorbek' 'Islombek' 'Samandar' 'Ibrohimjon' 'Nomonjon' 'Akmaljon'
 'Islombek']
[[ 0.27984377  0.53962617  1.51398273 -0.13012728]
 [ 0.31901309  0.3681482  -3.04922905  0.37138723]
 [-0.58031246  1.25694581  0.02485967  0.0928954 ]
 [-1.18750681 -0.34246611  0.95577529 -1.6665418 ]
 [ 0.19622189  0.13028666 -0.73839528  0.53451725]
 [ 0.00444716  0.49056727  0.59123508 -1.56253269]
 [ 0.22738966 -1.46915135  0.471569   -0.85743321]]


In [ ]:
mask = (names == 'Sardorbek') | (names == 'Samandar')   #ismi Sardorbek yoki Samandar bo'lgan qiymatlatni shabloni
mask

array([ True, False,  True, False, False, False, False])

In [ ]:
data[mask]  #qiymati Sardorbek va Samandar tegishli ma'lumotlarni chiqarish

array([[ 0.27984377,  0.53962617,  1.51398273, -0.13012728],
       [-0.58031246,  1.25694581,  0.02485967,  0.0928954 ]])

In [ ]:
data

array([[ 0.27984377,  0.53962617,  1.51398273, -0.13012728],
       [ 0.31901309,  0.3681482 , -3.04922905,  0.37138723],
       [-0.58031246,  1.25694581,  0.02485967,  0.0928954 ],
       [-1.18750681, -0.34246611,  0.95577529, -1.6665418 ],
       [ 0.19622189,  0.13028666, -0.73839528,  0.53451725],
       [ 0.00444716,  0.49056727,  0.59123508, -1.56253269],
       [ 0.22738966, -1.46915135,  0.471569  , -0.85743321]])

In [ ]:
data[data < 0]  = 0 # data dagi qiymati 0 dan kichik bo'lgan qiymatlarni 0 ga almashtirish
data

array([[0.27984377, 0.53962617, 1.51398273, 0.        ],
       [0.31901309, 0.3681482 , 0.        , 0.37138723],
       [0.        , 1.25694581, 0.02485967, 0.0928954 ],
       [0.        , 0.        , 0.95577529, 0.        ],
       [0.19622189, 0.13028666, 0.        , 0.53451725],
       [0.00444716, 0.49056727, 0.59123508, 0.        ],
       [0.22738966, 0.        , 0.471569  , 0.        ]])

In [ ]:
rand_num = np.arange(0, 9, 1).reshape(3, 3)
rand_num

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
slice_arr = rand_num[2, 0:2]
slice_arr

array([6, 7])