<a href="https://colab.research.google.com/github/Chaqmoqjon/MohirdevNumPY/blob/main/5_Transposing%26Swapping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A = np.arange(6).reshape(3, 2)  # 0 dan 6 gacha 3 ga 2 o'lchamli massiv
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
A.T   # Transpose o'lchamini o'zgartirish, maximum 2D o'zgartiriladi

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
A.swapaxes(1, 0)  # Transpose kabi ishlaydi, hamma turdagi massivlar uchun ishlaydi

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
np.dot(A, A.T)  # A * A.T  hosil bo'lgan massiv

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])