<a href="https://colab.research.google.com/github/Chaqmoqjon/MohirdevNumPY/blob/main/6_Universal_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#  Uniriy guruhi funksiyalari  faqat bitta arr qabul qiladi  not (arr1, arr2)

In [ ]:
np.sqrt(arr)  # kvadrad ildizga olish,

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.square(arr) # kavdratga oshiradi

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
np.exp(arr)  # sonlarni exponentini qaytaradi,  e ~ 2.71828183, ekponent darajalari

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.log(arr[1:])  # logirifmlarni hisoblaydi (loge). 0 da xato bor

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
arr_haq = np.random.randn(6)  # 6 ta random son
arr_haq

array([-0.29572655,  0.10456893,  1.32180628,  0.19640997,  1.51973034,
       -1.09871259])

In [ ]:
qoldiq, butun = np.modf(arr_haq)  #  qoldiq va butun qismini ikkita massivga oladi

In [ ]:
print(qoldiq)
print(butun)

[-0.29572655  0.10456893  0.32180628  0.19640997  0.51973034 -0.09871259]
[-0.  0.  1.  0.  1. -1.]


In [ ]:
np.sign(arr_haq)  # arr_haq ning ishoralarini  -1 va 1 ko'rinishida qaytaradi

array([-1.,  1.,  1.,  1.,  1., -1.])

In [ ]:
np.isnan(arr_haq)  # Nan qiymati bo'lsa True qaytaradi

array([False, False, False, False, False, False])

In [ ]:
arr_haq[0] = np.NaN  # qiymatini NaN ga o'zgartirish
arr_haq

array([        nan,  0.10456893,  1.32180628,  0.19640997,  1.51973034,
       -1.09871259])

In [ ]:
np.isnan(arr_haq) # Nan qiymati bo'lsa True qaytaradi

array([ True, False, False, False, False, False])

In [ ]:
arr2 = np.random.randn(6)
arr3 = np.random.randn(6)

In [ ]:
arr2

array([-0.30313405, -0.01151554, -1.18090512, -0.71227244, -1.34465908,
        0.47414537])

In [ ]:
arr3

array([ 1.09043976, -0.18345381, -0.00914177, -1.46137595,  0.39254571,
        1.04968222])

In [ ]:
np.add(arr2, arr3)  # arr2 va arr3 ni mos ravishda qo'shadi

array([ 0.78730571, -0.19496935, -1.19004689, -2.17364838, -0.95211337,
        1.52382759])

In [ ]:
arr2 + arr3  # add() bilan bir hil ishlaydi

array([ 0.78730571, -0.19496935, -1.19004689, -2.17364838, -0.95211337,
        1.52382759])

In [ ]:
np.multiply(arr2, arr3)  #arr2 va arr3 ni mos ravishda ko'paytiradi

array([-0.33054942,  0.00211257,  0.01079556,  1.04089781, -0.52784015,
        0.49770197])

In [ ]:
arr2 * arr3  # multiplay() bilan bir hil ishlaydi

array([-0.33054942,  0.00211257,  0.01079556,  1.04089781, -0.52784015,
        0.49770197])

In [ ]:
arr2

array([-0.30313405, -0.01151554, -1.18090512, -0.71227244, -1.34465908,
        0.47414537])

In [ ]:
arr3

array([ 1.09043976, -0.18345381, -0.00914177, -1.46137595,  0.39254571,
        1.04968222])

In [ ]:
np.maximum(arr2, arr3)  #arr2 va arr3 ni mos ravishda kattasini chiqaradi

array([ 1.09043976, -0.01151554, -0.00914177, -0.71227244,  0.39254571,
        1.04968222])