<a href="https://colab.research.google.com/github/Chaqmoqjon/MohirdevNumPY/blob/main/7_Arr_Or_Pr_1_Logical_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [ ]:
con = np.array([True, False, True, True, False])

In [ ]:
result = np.where(con, xarr, yarr)  # agar True bo'lsa xarr, False bo'lsa yarr qiymatini oladi
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [ ]:
arr = np.random.randn(4, 4)
arr

array([[-0.80843593, -0.33296458,  2.23521449,  0.06222656],
       [-0.41588889, -0.53749209, -1.68858604,  1.31700679],
       [-0.23752672, -0.81155366,  0.42603411,  0.91260408],
       [ 0.76595913,  0.44586332, -0.1063478 , -0.98772196]])

In [ ]:
results = np.where(arr < 0, -2, 2)  # manfiy qiymatlarni -2 ga, musbatlarni 2 ga aylantiradi
results

array([[-2, -2,  2,  2],
       [-2, -2, -2,  2],
       [-2, -2,  2,  2],
       [ 2,  2, -2, -2]])