<a href="https://colab.research.google.com/github/Chaqmoqjon/MohirdevNumPY/blob/main/8_Arr_Or%262_Arithmetic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1 = np.arange(6).reshape(2,3)
arr2 = np.arange(6, 12).reshape(2,3)

In [ ]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
arr1 * arr2  # arr1 va arr2 mos ravishta ko'paytirish

array([[ 0,  7, 16],
       [27, 40, 55]])

In [ ]:
arr2 / arr1 # arr1 va arr2 mos ravishta bo'lish

<ipython-input-7-e2e60495effe>:1: RuntimeWarning: divide by zero encountered in divide
  arr2/arr1


array([[inf, 7. , 4. ],
       [3. , 2.5, 2.2]])

In [ ]:
arr1 + arr2 # arr1 va arr2 mos ravishta qo'shish

array([[ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
arr2 - arr1 # arr1 va arr2 mos ravishta ayirish

array([[6, 6, 6],
       [6, 6, 6]])

In [ ]:
arr2 ** 2  # darajaga oshirish

array([[ 36,  49,  64],
       [ 81, 100, 121]])

In [ ]:
arr2 ** 0.5  # ildizga olish

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])