<a href="https://colab.research.google.com/github/Chaqmoqjon/NumPY/blob/main/9_Arr_Orr_1_Math_Stat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randn(5, 4)
arr

array([[-0.21198463, -0.21378355, -0.58715896,  0.2270371 ],
       [ 1.15938821, -0.01775898, -1.1658198 , -0.26446409],
       [-1.60586421, -2.24481029, -1.59576023, -0.74549223],
       [-1.13431175, -1.38086902, -1.15200171,  0.05939228],
       [ 1.4671158 ,  0.22662874, -0.78230029,  1.93528486]])

In [ ]:
arr.sum()  #umumiy qiymatini topadi

-8.027532747992739

In [ ]:
np.sum(arr)  #umumiy qiymatini topadi

-8.027532747992739

In [ ]:
arr.sum(axis = 1)  # har bir qatorning umumiy qiymati

array([-0.78589004, -0.28865467, -6.19192695, -3.60779019,  2.84672911])

In [ ]:
arr.mean() #o'tacha qiymatini topadi

-0.4013766373996369

In [ ]:
arr.mean(axis = 1) # har bir qatorning o'tacha qiymati
np.mean(arr, axis=0) # har bir qatorning o'tacha qiymati

array([-0.06513132, -0.72611862, -1.0566082 ,  0.24235158])

In [ ]:
arr.sum(axis = 0)  # har bir ustunning umumiy qiymati

array([-0.32565659, -3.63059309, -5.28304098,  1.21175792])

In [ ]:
arr2 = np.arange(8)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr2.cumsum() # o'zigacha bo'lgan qiymatlarni qo'shib yozadi

array([ 0,  1,  3,  6, 10, 15, 21, 28])