<a href="https://colab.research.google.com/github/Chaqmoqjon/NumPY/blob/main/Copy_of_mohirdev_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [ ]:
import numpy as np
np.version
np.show_config

<function numpy.__config__.show(mode='stdout')>

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [ ]:
num_arr = np.array([2, 4, 6, 8, 5, 9, 0])
num_arr

array([2, 4, 6, 8, 5, 9, 0])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [ ]:
zeros_nine = np.zeros(9)
zeros_nine

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [ ]:
num_arr2 = np.array([2, 4, 6, 8, 5, 9, 0])
num_arr2.size
num_arr2.itemsize

8

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
np.info(num_arr2)

class:  ndarray
shape:  (7,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x576cbb7d1f40
byteorder:  little
byteswap:  False
type: int64


#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [ ]:
arr12 = np.zeros(12)
arr12[6] = 1
arr12

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [ ]:
vektor_20 = np.arange(20, 59)
vektor_20

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [ ]:
vektor_1 = np.arange(5, 50, 5)
vektor_1[::-1]

array([45, 40, 35, 30, 25, 20, 15, 10,  5])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [ ]:
reshape_12  =  np.arange(12, 21).reshape((3, 3))
reshape_12

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [ ]:
find_zero = np.nonzero([3, 7, 0, 0, 9, 0])
find_zero

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [ ]:
random_int = np.random.randint(10, 99, 8).reshape((2, 2, 2))
random_int

array([[[37, 13],
        [53, 36]],

       [[67, 26],
        [96, 43]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [ ]:
random_9 = np.random.randn(81).reshape((9, 9))
np.max(random_9)
random_9.min()

-2.0707502980692745

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [ ]:
0 * np.nan

nan

In [ ]:
np.nan == np.nan

False

In [ ]:
np.inf >  np.nan

False

In [ ]:
np.nan - np.nan

nan

In [ ]:
np.nan in set([np.nan])

True

In [ ]:
0.7 == 7 * 0.1

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [ ]:
arr63 = np.random.random(18).reshape((6, 3))
arr34 = np.random.random(12).reshape((3, 4))
np.dot(arr63, arr34)

array([[0.88701159, 1.48696342, 1.07397078, 0.71010877],
       [0.19821142, 0.81995042, 0.47629532, 0.57095174],
       [0.35215571, 0.25828082, 0.47707631, 0.16238014],
       [0.3749077 , 0.65110128, 0.61960668, 0.43710829],
       [0.49024479, 0.84450656, 0.81667384, 0.57320778],
       [0.81690005, 1.35139248, 1.04585347, 0.68863291]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
arr_01 = np.array([1, 3, 4])
arr_02 = np.array([2, 3, 1])

In [ ]:
arr_01 >  arr_02

array([False, False,  True])

In [ ]:
arr_01 >=  arr_02

array([False,  True,  True])

In [ ]:
arr_01 <  arr_02

array([ True, False, False])

In [ ]:
arr_01 <=  arr_02

array([ True,  True, False])

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)

<ipython-input-60-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [ ]:
np.array(0) // np.array(0)

<ipython-input-59-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [ ]:
np.array([np.nan]).astype(int).astype(float)

<ipython-input-61-ea171f4782f5>:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [ ]:
random_01 = np.random.randint(2, 20, 10)
random_02 = np.random.randint(2, 20, 10)
np.intersect1d(random_01, random_02)

array([ 2,  5,  9, 14])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [ ]:
random_03 = np.random.random((20))
random_04 = np.random.randn((20))
#1
np.floor(random_03)
np.floor(random_04)
#2
random_03 .astype(int)
random_04 .astype(int)
#3
np.trunc(random_03)
np.trunc(random_04)

array([-2., -0.,  0., -0.,  0., -1., -2.,  0., -3., -0., -0., -1., -0.,
        1.,  0., -0., -0.,  1., -0.,  0.])

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [ ]:
matrix_3x3 = np.arange(0, 2, 0.24).reshape((3, 3))
matrix_3x3

array([[0.  , 0.24, 0.48],
       [0.72, 0.96, 1.2 ],
       [1.44, 1.68, 1.92]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [ ]:
rand_vek10 = np.random.random(10)
np.sort(rand_vek10)

array([0.23456756, 0.31045372, 0.32519931, 0.36523838, 0.37735128,
       0.58328413, 0.73552224, 0.74857644, 0.86841069, 0.96169366])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [ ]:
a = np.random.random(10)
b = np.random.random(10)

np.array_equal(a, b)
np.allclose(a, b)

False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [ ]:
a = np.random.randint(1, 100, 18).reshape(6,3)
b = np.random.randint(1, 100, 12).reshape(3,4)

np.dot(a, b)


array([[ 3901,  1981, 15256, 11996],
       [ 7561,  4691, 14146, 15164],
       [ 7372,  4436, 13800, 14490],
       [ 6444,  5738, 12862, 17231],
       [ 4373,  4227,  9606, 12984],
       [ 7065,  4705, 17920, 17900]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [ ]:
random_5 = np.random.randint(1, 50, 5)
max_ind = np.argmax(random_5)
random_5[max_ind] = 0
random_5

array([26, 27,  0, 30, 29])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [ ]:
np.datetime64('2024-11-14')
np.datetime64('2024-11-15')
np.datetime64('2024-11-16')

delta_time = np.timedelta64(5, 'h')
print(delta_time)

5 hours


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [ ]:
dates = np.arange('2016-01-01', '2016-02-01', dtype='datetime64[D]')

print(dates)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [ ]:
tas_son = np.random.randn(20)
tas_mus = tas_son[tas_son > 0]
np.floor(tas_mus)
tas_mus.astype(int)
np.trunc(tas_mus)

array([0., 0., 1., 0., 1., 0., 1., 0., 0., 0.])

#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [ ]:
%%time
ixtiyor = np.random.random(200000)
ixtiyor.sum()

CPU times: user 4.12 ms, sys: 0 ns, total: 4.12 ms
Wall time: 3.48 ms


99939.62621107456

In [ ]:
%%time
ixtiyor2 = np.random.random(200000)
np.add.reduce(ixtiyor2)


CPU times: user 5.56 ms, sys: 0 ns, total: 5.56 ms
Wall time: 6.03 ms


99937.90619874568

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [ ]:
v1 = [1, 2, 3, 4, 5]

arr1 = len(v1) * 4 - 3
new_arr = np.zeros(arr1, dtype=int)

new_arr[::4] = v1

new_arr


array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [ ]:
arr = np.arange(1, 15)
window_size = 4
stride = arr.strides[0]

shape = (len(arr) - window_size + 1, window_size)
strides = (stride, stride)

b = as_strided(arr, shape=shape, strides=strides)

print(b)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [ ]:
arr = np.array([3, 7, 2, 7, 7, 1, 4, 4, 2, 7, 3, 2, 1, 4])

counts = np.bincount(arr)  # har bir son necha martta takrorlanganini sanaydi, faqat butn sonlar bilan ishlaydi
kop_tak = np.argmax(counts) # eng kattasini  qaytaradi

kop_tak


7

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`

In [ ]:
# 1000 ta insonning BMI ni hosoblab guruhlarga bo'lib chiqing. Ma'lumotlar random holatda kelsin
vazni = np.random.randint(50, 150, 1000)
boyi = np.random.randint(150, 200, 1000)

BMI_simple = vazni / ((boyi / 100) ** 2)
BMI = BMI_simple.round(2)

Under_Weight = BMI[np.where(BMI < 18.5)]
Normal = BMI[np.where((BMI >18.5) & (BMI < 25))]
Over_Weight = BMI[np.where((BMI > 25) & (BMI < 30))]
Obese = BMI[np.where((BMI >30) & (BMI < 35))]
Extremely_Obese = BMI[np.where(BMI > 35)]

